// Known Comms Database name strings, used to label hashes in
// CommsToolListDefinition (0x45) / CommsToolList (0x46) resources.
//
// The resources store only Language hashes (JAMCRC — see languageHash.ts);
// the strings themselves were recovered from the game executable and are
// catalogued on the wiki's Comms Tool List Definition/Definitions subpage.
// This table is the union of every name in those tables: 4 definition names
// (Gameplay, Car, Motorbike, PassThePadDef), 8 category names, and 342 field
// names across all known definitions. JAMCRC has no collisions within this
// set (verified), so the reverse lookup is unambiguous.
//
// Generated from docs/CommsToolListDefinition_Definitions.md in the parent
// repo; regenerate by re-deriving the union of the Category and Field columns
// if the wiki tables grow.

import { languageHash } from './languageHash';

export const KNOWN_COMMS_DEFINITION_NAMES = ['Gameplay', 'Car', 'Motorbike', 'PassThePadDef'] as const;

export const KNOWN_COMMS_TOOL_NAMES = [
	'Audio', 'Camera', 'Collision',
	'Physics', 'Scoring', 'ServerControls',
	'TakedownPhysics', 'Wheelie', 'ADHESIVE_LIMIT',
	'ANALOGUE_HIGHEST_SCORE', 'BIKE_BOOSTED_HARMONIC', 'BIKE_MAX_SPEED_PEAKING_EQ_GAIN',
	'BIKE_MAX_SPEED_VOL_GAIN', 'BIKE_MAX_STEER_PEAKING_EQ_GAIN', 'BIKE_MAX_STEER_PITCH',
	'BIKE_MAX_STEER_VOL_GAIN', 'BIKE_MAX_WHEELIE_PEAKING_EQ_GAIN', 'BIKE_MAX_WHEELIE_VOL_GAIN',
	'BIKE_MIN_SPEED_VOL_GAIN', 'BIKE_MIN_WHEELIE_VOL_GAIN', 'BOOST_LIMIT',
	'BOOST_MULTIPLIER', 'BRAKE_TO_HIGH_TORQUE', 'BRAKE_TO_MIDDLE_TORQUE',
	'BRAKE_TO_TORQUE_RATE', 'CAMERA_Y_OFFSET', 'CARS_AVAILABILITY',
	'COUNTER_STEER_RATE', 'DESIRED_ROLL_TO_IMPULSE', 'DESIRED_WHEELIE_LEAN_TO_IMPULSE',
	'DESIRED_WHEELIE_LEAN_TO_IMPULSE_COUNTER_STEER', 'DIGITAL_BASE_SCORE', 'DISABLE_PROGRESSION_CARS',
	'DRAG', 'DYNAMIC_FRICTION_COEFF', 'EVENT_GRAD_ID',
	'FORWARD_STEERING_TO_WHEELIE_SCALE', 'FRONT_CLIP_PLANE_MAX_OFFSET', 'FRONT_CLIP_PLANE_MAX_ROTATION',
	'FRONT_CLIP_PLANE_MIN_OFFSET', 'FRONT_CLIP_PLANE_MIN_ROTATION', 'GAS_LETOFF_TO_HIGH_TORQUE',
	'GAS_LETOFF_TO_MIDDLE_TORQUE', 'GAS_LETOFF_TO_TORQUE_RATE', 'GAS_POWERON_TO_HIGH_TORQUE',
	'GAS_POWERON_TO_MIDDLE_TORQUE', 'GAS_POWERON_TO_TORQUE_RATE', 'GRAD_ID_0',
	'GRAD_ID_1', 'GRAD_ID_2', 'GRAD_ID_3',
	'GRAD_ID_4', 'GRAD_ID_5', 'GRAD_ID_6',
	'GRAD_ID_7', 'GRINDING_TIME_BEFORE_CRASH', 'GROUND_CLIP_PLANE_MAX_OFFSET_FROM_ROAD',
	'GROUND_CLIP_PLANE_MAX_SPEED_MPH', 'GROUND_CLIP_PLANE_MIN_SPEED_MPH', 'GROUND_CLIP_PLANE_ROAD_HEIGHT',
	'HALF_SPEED_TORQUE_AXIS_ANGLE', 'HALF_SPEED_WHEELIE_LEAN_ANGLE_DEGREES', 'HALF_WHEELIE_SCALE_PITCH_DAMPING',
	'HEAD_ON_ADDITONAL_VULNERABILITY', 'HIGH_SPEED_BACKWARD_STEERING_TO_WHEELIE', 'HIGH_SPEED_MAINTAINED_WHEELIE_ANGLE_DEGREES',
	'INITIAL_WALL_IMPACT_STEERING', 'LAT_GRIP_CURVE_FALL_COEFF', 'LAT_GRIP_CURVE_FLOOR_SLIP_RATIO',
	'LAT_GRIP_CURVE_PEAK_COEFF', 'LAT_GRIP_CURVE_PEAK_SLIP_RATIO', 'LEAN_FACTOR_CLAMP_TO_ZERO_IN_WHEELIE',
	'LEAN_FACTOR_DECAY_IN_WHEELIE', 'LONG_FORCE_BIAS', 'LONG_GRIP_CURVE_FALL_COEFF',
	'LONG_GRIP_CURVE_FLOOR_SLIP_RATIO', 'LONG_GRIP_CURVE_PEAK_COEFF', 'LONG_GRIP_CURVE_PEAK_SLIP_RATIO',
	'LOW_SPEED_BACKWARD_STEERING_TO_WHEELIE', 'LOW_SPEED_MAINTAINED_WHEELIE_ANGLE_DEGREES', 'MAX_ACCEL_FORCE_MAGNITUDE',
	'MAX_ANGLE', 'MAX_NATURAL_WHEELIE_ANGLE_DEGREES', 'MAX_SPEED_FOR_SMALL_WHEELIE_ANGLE',
	'MAX_SPEED_TORQUE_AXIS_ANGLE', 'MAX_SPEED_WHEELIE_LEAN_ANGLE_DEGREES', 'MAX_WHEELIE_SCALE_PITCH_DAMPING',
	'MIN_ANGLE', 'MIN_SLAM_STEERING_AI', 'MIN_SLAM_STEERING_NETWORK',
	'MIN_SLAM_STEERING_PLAYER', 'MIN_SPEED_FOR_LARGE_WHEELIE_ANGLE', 'MIN_STEER_ANGLE_IN_WHEELIE',
	'MIN_WHEELIE_SCALE_TO_ENTER_WHEELIE', 'OFFLINE_VULNERABILITY_FACTOR_AI', 'OFFLINE_VULNERABILITY_FACTOR_PLAYER',
	'OFFLINE_VULNERABILITY_FALLOFF_AI', 'OFFLINE_VULNERABILITY_FALLOFF_PLAYER', 'ONLINE_VULNERABILITY_FACTOR_AI',
	'ONLINE_VULNERABILITY_FACTOR_NETWORK', 'ONLINE_VULNERABILITY_FACTOR_PLAYER', 'ONLINE_VULNERABILITY_FALLOFF_AI',
	'ONLINE_VULNERABILITY_FALLOFF_NETWORK', 'ONLINE_VULNERABILITY_FALLOFF_PLAYER', 'REAR_CLIP_PLANE_MAX_OFFSET',
	'REAR_CLIP_PLANE_MAX_ROTATION', 'REAR_CLIP_PLANE_MIN_OFFSET', 'REAR_CLIP_PLANE_MIN_ROTATION',
	'REQUIRED_ACTION', 'REQUIRED_CARS_0', 'REQUIRED_CARS_1',
	'REQUIRED_CARS_10', 'REQUIRED_CARS_11', 'REQUIRED_CARS_12',
	'REQUIRED_CARS_13', 'REQUIRED_CARS_14', 'REQUIRED_CARS_15',
	'REQUIRED_CARS_2', 'REQUIRED_CARS_3', 'REQUIRED_CARS_4',
	'REQUIRED_CARS_5', 'REQUIRED_CARS_6', 'REQUIRED_CARS_7',
	'REQUIRED_CARS_8', 'REQUIRED_CARS_9', 'REWARD_0',
	'REWARD_1', 'REWARD_10', 'REWARD_11',
	'REWARD_12', 'REWARD_13', 'REWARD_14',
	'REWARD_15', 'REWARD_16', 'REWARD_17',
	'REWARD_18', 'REWARD_19', 'REWARD_2',
	'REWARD_20', 'REWARD_21', 'REWARD_22',
	'REWARD_23', 'REWARD_24', 'REWARD_25',
	'REWARD_26', 'REWARD_27', 'REWARD_28',
	'REWARD_29', 'REWARD_3', 'REWARD_30',
	'REWARD_31', 'REWARD_4', 'REWARD_5',
	'REWARD_6', 'REWARD_7', 'REWARD_8',
	'REWARD_9', 'REWARD_TYPE_0', 'REWARD_TYPE_1',
	'REWARD_TYPE_10', 'REWARD_TYPE_11', 'REWARD_TYPE_12',
	'REWARD_TYPE_13', 'REWARD_TYPE_14', 'REWARD_TYPE_15',
	'REWARD_TYPE_16', 'REWARD_TYPE_17', 'REWARD_TYPE_18',
	'REWARD_TYPE_19', 'REWARD_TYPE_2', 'REWARD_TYPE_20',
	'REWARD_TYPE_21', 'REWARD_TYPE_22', 'REWARD_TYPE_23',
	'REWARD_TYPE_24', 'REWARD_TYPE_25', 'REWARD_TYPE_26',
	'REWARD_TYPE_27', 'REWARD_TYPE_28', 'REWARD_TYPE_29',
	'REWARD_TYPE_3', 'REWARD_TYPE_30', 'REWARD_TYPE_31',
	'REWARD_TYPE_4', 'REWARD_TYPE_5', 'REWARD_TYPE_6',
	'REWARD_TYPE_7', 'REWARD_TYPE_8', 'REWARD_TYPE_9',
	'ROLL_COEFFICIENT', 'ROLL_DAMPENING', 'ROLL_FALLOFF_LOWER_DEGS',
	'ROLL_FALLOFF_UPPER_DEGS', 'ROLL_SPRING', 'SCORE_INTERVAL',
	'SHUNT_MAX_STRENGTH_MODIFIER_ONLINE', 'SHUNT_MIN_STRENGTH_MODIFIER_ONLINE', 'SHUNT_SITUATION_SCALES_AI_ON_AI',
	'SHUNT_SITUATION_SCALES_AI_ON_PLAYER', 'SHUNT_SITUATION_SCALES_NETWORK', 'SHUNT_SITUATION_SCALES_PLAYER_ON_AI',
	'SHUNT_SITUATION_VULNERABLE_TIMES_AI_ON_AI', 'SHUNT_SITUATION_VULNERABLE_TIMES_AI_ON_PLAYER', 'SHUNT_SITUATION_VULNERABLE_TIMES_NETWORK',
	'SHUNT_SITUATION_VULNERABLE_TIMES_PLAYER_ON_AI', 'SIDE_CLIP_PLANE_MAX_OFFSET', 'SIDE_CLIP_PLANE_MAX_ROTATION',
	'SIDE_CLIP_PLANE_MIN_OFFSET', 'SIDE_CLIP_PLANE_MIN_ROTATION', 'SIDE_ON_ADDITONAL_VULNERABILITY',
	'SLAM_MAX_DISTANCE_MODIFIER_ONLINE', 'SLAM_MAX_STRENGTH_MODIFIER_ONLINE', 'SLAM_MIN_DISTANCE_MODIFIER_ONLINE',
	'SLAM_MIN_STRENGTH_MODIFIER_ONLINE', 'SLAM_RECOVERY_TIMES_AI_ON_AI', 'SLAM_RECOVERY_TIMES_AI_ON_PLAYER',
	'SLAM_RECOVERY_TIMES_NETWORK', 'SLAM_RECOVERY_TIMES_PLAYER_ON_AI', 'SLAM_RECOVERY_TIMES_ROAD_RAGE_AI_ON_AI',
	'SLAM_RECOVERY_TIMES_ROAD_RAGE_AI_ON_PLAYER', 'SLAM_RECOVERY_TIMES_ROAD_RAGE_NETWORK', 'SLAM_RECOVERY_TIMES_ROAD_RAGE_PLAYER_ON_AI',
	'SLAM_SITUATION_SCALES_AI_ON_AI', 'SLAM_SITUATION_SCALES_AI_ON_PLAYER', 'SLAM_SITUATION_SCALES_NETWORK',
	'SLAM_SITUATION_SCALES_PLAYER_ON_AI', 'SLAM_SITUATION_VULNERABLE_TIMES_AI_ON_AI', 'SLAM_SITUATION_VULNERABLE_TIMES_AI_ON_PLAYER',
	'SLAM_SITUATION_VULNERABLE_TIMES_NETWORK', 'SLAM_SITUATION_VULNERABLE_TIMES_PLAYER_ON_AI', 'SPEED_FOR_HIGH_SPEED_TRAFFIC_COLLISION',
	'SPEED_FOR_LOW_SPEED_TRAFFIC_COLLISION', 'SPEED_FOR_MAX_LEAN', 'SPEED_FOR_MAX_STEERING_ANGLE_IN_WHEELIE',
	'SPEED_FOR_MAX_STEER_ANGLE', 'SPEED_FOR_MAX_TORQUE', 'SPEED_FOR_NO_LEAN',
	'SPEED_LOSS_TO_CRASH_WITH_TRAFFIC_AT_HIGH_SPEED', 'SPEED_LOSS_TO_CRASH_WITH_TRAFFIC_AT_LOW_SPEED', 'SPEED_MPH_FOR_MAX_BACKWARD_STEERING',
	'SPEED_MPH_FOR_MIN_BACKWARD_STEERING', 'SPEED_MPH_FOR_NO_ACCEL_FORCE', 'STATIC_FRICTION_COEFF',
	'STEERING_DECAY', 'STEERING_DECAY_IN_WHEELIE', 'STEERING_TO_HIGH_TORQUE',
	'STEERING_TO_MIDDLE_TORQUE', 'STEERING_TO_WHEELIE_LEAN_SCALE', 'STEER_ANGLE_RANGE_IN_WHEELIE',
	'STEER_RATE', 'STEER_RATE_IN_WHEELIE', 'STREAMLINING_ACCELERATION',
	'STREAMLINING_MAX_SPEED', 'TEMP_EXTRA_CAR_0', 'TEMP_EXTRA_CAR_1',
	'TEMP_EXTRA_CAR_10', 'TEMP_EXTRA_CAR_11', 'TEMP_EXTRA_CAR_12',
	'TEMP_EXTRA_CAR_13', 'TEMP_EXTRA_CAR_14', 'TEMP_EXTRA_CAR_15',
	'TEMP_EXTRA_CAR_16', 'TEMP_EXTRA_CAR_17', 'TEMP_EXTRA_CAR_18',
	'TEMP_EXTRA_CAR_19', 'TEMP_EXTRA_CAR_2', 'TEMP_EXTRA_CAR_20',
	'TEMP_EXTRA_CAR_21', 'TEMP_EXTRA_CAR_22', 'TEMP_EXTRA_CAR_23',
	'TEMP_EXTRA_CAR_24', 'TEMP_EXTRA_CAR_25', 'TEMP_EXTRA_CAR_26',
	'TEMP_EXTRA_CAR_27', 'TEMP_EXTRA_CAR_28', 'TEMP_EXTRA_CAR_29',
	'TEMP_EXTRA_CAR_3', 'TEMP_EXTRA_CAR_30', 'TEMP_EXTRA_CAR_31',
	'TEMP_EXTRA_CAR_32', 'TEMP_EXTRA_CAR_33', 'TEMP_EXTRA_CAR_34',
	'TEMP_EXTRA_CAR_35', 'TEMP_EXTRA_CAR_36', 'TEMP_EXTRA_CAR_37',
	'TEMP_EXTRA_CAR_38', 'TEMP_EXTRA_CAR_39', 'TEMP_EXTRA_CAR_4',
	'TEMP_EXTRA_CAR_40', 'TEMP_EXTRA_CAR_41', 'TEMP_EXTRA_CAR_42',
	'TEMP_EXTRA_CAR_43', 'TEMP_EXTRA_CAR_44', 'TEMP_EXTRA_CAR_45',
	'TEMP_EXTRA_CAR_46', 'TEMP_EXTRA_CAR_47', 'TEMP_EXTRA_CAR_48',
	'TEMP_EXTRA_CAR_49', 'TEMP_EXTRA_CAR_5', 'TEMP_EXTRA_CAR_50',
	'TEMP_EXTRA_CAR_51', 'TEMP_EXTRA_CAR_52', 'TEMP_EXTRA_CAR_53',
	'TEMP_EXTRA_CAR_54', 'TEMP_EXTRA_CAR_55', 'TEMP_EXTRA_CAR_56',
	'TEMP_EXTRA_CAR_57', 'TEMP_EXTRA_CAR_58', 'TEMP_EXTRA_CAR_59',
	'TEMP_EXTRA_CAR_6', 'TEMP_EXTRA_CAR_60', 'TEMP_EXTRA_CAR_61',
	'TEMP_EXTRA_CAR_62', 'TEMP_EXTRA_CAR_63', 'TEMP_EXTRA_CAR_7',
	'TEMP_EXTRA_CAR_8', 'TEMP_EXTRA_CAR_9', 'TIME_WITH_GAS_FOR_MAX_ACCEL_FORCE',
	'TIME_WITH_GAS_FOR_ZERO_ACCEL_FORCE', 'TORQUE_AXIS_ANGLE_MAX_SPEED_MPH', 'VEL_TO_LEAN_FACTOR_HIGH_SPEED',
	'VEL_TO_LEAN_FACTOR_LOW_SPEED', 'VICTIM_SLAM_POWER_MAX', 'VICTIM_SLAM_POWER_MAX_ONLINE',
	'VICTIM_SLAM_POWER_MIN', 'VICTIM_SLAM_POWER_MIN_ONLINE', 'VICTIM_SLAM_POWER_SCALE',
	'VICTIM_SLAM_POWER_SCALE_ONLINE', 'WALL_IMPACT_SLOWDOWN', 'WALL_IMPACT_SLOWDOWN_MIN_SPEED',
	'WALL_IMPACT_STEERING_MIN_SPEED', 'WALL_IMPACT_STEERING_TIME', 'WALL_RECOIL_VELOCITY_COMPONENT',
	'WALL_RECOIL_VELOCITY_SCALE', 'WALL_SCRAPE_BASE_DANGER_DECREMENT', 'WALL_SCRAPE_BASE_DANGER_INCREMENT',
	'WALL_SCRAPE_MIN_VELOCITY', 'WALL_SCRAPE_VELOCITY_COMPONENT', 'WALL_SCRAPE_VELOCITY_SCALE',
	'WHEELIE_DOUGHNUT_BACKWARD_STEERING_TO_WHEELIE', 'WHEELIE_DOUGHNUT_STEERING_DEAD_ZONE', 'WHEELIE_LEAN_ANGLE_MAX_SPEED_MPH',
	'WHEELIE_SCALE_FOR_MAX_ACCEL_FORCE', 'WHEELIE_SCALE_FOR_ZERO_ACCEL_FORCE', 'WORLD_CRASH_THRESHOLD',
	'WORLD_HEAD_ON_CRASH_SPEED', 'WORLD_SIDE_ON_CRASH_SPEED', 'ZERO_SPEED_TORQUE_AXIS_ANGLE',
	'ZERO_SPEED_WHEELIE_LEAN_ANGLE_DEGREES', 'ZERO_WHEELIE_SCALE_PITCH_DAMPING',
] as const;

let lookup: Map<number, string> | null = null;

/**
 * Resolve a Language hash back to its known Comms Database name (definition,
 * category, or field name). Returns null for hashes outside the catalogue —
 * callers must keep the raw hash as the source of truth.
 */
export function resolveCommsToolName(hash: number): string | null {
	if (lookup === null) {
		lookup = new Map();
		for (const name of [...KNOWN_COMMS_DEFINITION_NAMES, ...KNOWN_COMMS_TOOL_NAMES]) {
			lookup.set(languageHash(name), name);
		}
	}
	return lookup.get(hash >>> 0) ?? null;
}
