// Lookup table from handler key → ResourceSchema. Generated by hand;
// every key here points at the schema that drives the schema-editor
// hierarchy / inspector for that resource type. Keys not listed here have
// no schema yet (renderable's tree comes from RenderablePage's synthetic
// root, polygonSoupList from PolygonSoupListPage's bundled picker, etc.).
//
// Used by the WorkspaceEditor to look up a resource's schema when the
// user selects it in the tree, so the right-hand inspector can render the
// generic schema form for any resource type.

import type { ResourceSchema } from '../types';
import { aemsBankResourceSchema } from './aemsBank';
import { aiSectionsResourceSchema } from './aiSections';
import { aptDataResourceSchema } from './aptData';
import { challengeListResourceSchema } from './challengeList';
import { csisResourceSchema } from './csis';
import { colourCubeResourceSchema } from './colourCube';
import { commsToolListResourceSchema } from './commsToolList';
import { commsToolListDefinitionResourceSchema } from './commsToolListDefinition';
import { environmentDictionaryResourceSchema } from './environmentDictionary';
import { environmentKeyframeResourceSchema } from './environmentKeyframe';
import { environmentTimeLineResourceSchema } from './environmentTimeLine';
import { flaptFileResourceSchema } from './flaptFile';
import { fontResourceSchema } from './font';
import { genericRwacWaveContentResourceSchema } from './genericRwacWaveContent';
import { guiPopupResourceSchema } from './guiPopup';
import { hudMessageResourceSchema } from './hudMessage';
import { hudMessageSequenceResourceSchema } from './hudMessageSequence';
import { hudMessageSequenceDictionaryResourceSchema } from './hudMessageSequenceDictionary';
import { iceTakeDictionaryResourceSchema } from './iceTakeDictionary';
import { idListResourceSchema } from './idList';
import { instanceListResourceSchema } from './instanceList';
import { languageResourceSchema } from './language';
import { massiveLookupTableResourceSchema } from './massiveLookupTable';
import { nicotineResourceSchema } from './nicotine';
import { particleDescriptionResourceSchema } from './particleDescription';
import { particleDescriptionCollectionResourceSchema } from './particleDescriptionCollection';
import { playerCarColoursResourceSchema } from './playerCarColours';
import { registryResourceSchema } from './registry';
import { polygonSoupListResourceSchema } from './polygonSoupList';
import { propGraphicsListResourceSchema } from './propGraphicsList';
import { propInstanceDataResourceSchema } from './propInstanceData';
import { propPhysicsResourceSchema } from './propPhysics';
import { renderableResourceSchema } from './renderable';
import { snapshotDataResourceSchema } from './snapshotData';
import { splicerResourceSchema } from './splicer';
import { staticSoundMapResourceSchema } from './staticSoundMap';
import { streetDataResourceSchema } from './streetData';
import { textureResourceSchema } from './texture';
import { textureNameMapResourceSchema } from './textureNameMap';
import { trafficDataResourceSchema } from './trafficData';
import { triggerDataResourceSchema } from './triggerData';
import { vehicleListResourceSchema } from './vehicleList';
import { vfxMeshCollectionResourceSchema } from './vfxMeshCollection';
import { wheelListResourceSchema } from './wheelList';
import { vfxPropCollectionResourceSchema } from './vfxPropCollection';
import { worldPainter2DResourceSchema } from './worldPainter2D';
import { zoneListResourceSchema } from './zoneList';

const RESOURCE_SCHEMAS: Record<string, ResourceSchema> = {
	aiSections: aiSectionsResourceSchema,
	aptData: aptDataResourceSchema,
	aemsBank: aemsBankResourceSchema,
	challengeList: challengeListResourceSchema,
	csis: csisResourceSchema,
	colourCube: colourCubeResourceSchema,
	commsToolList: commsToolListResourceSchema,
	commsToolListDefinition: commsToolListDefinitionResourceSchema,
	environmentDictionary: environmentDictionaryResourceSchema,
	environmentKeyframe: environmentKeyframeResourceSchema,
	environmentTimeLine: environmentTimeLineResourceSchema,
	flaptFile: flaptFileResourceSchema,
	font: fontResourceSchema,
	genericRwacWaveContent: genericRwacWaveContentResourceSchema,
	guiPopup: guiPopupResourceSchema,
	hudMessage: hudMessageResourceSchema,
	hudMessageSequence: hudMessageSequenceResourceSchema,
	hudMessageSequenceDictionary: hudMessageSequenceDictionaryResourceSchema,
	iceTakeDictionary: iceTakeDictionaryResourceSchema,
	idList: idListResourceSchema,
	instanceList: instanceListResourceSchema,
	language: languageResourceSchema,
	massiveLookupTable: massiveLookupTableResourceSchema,
	nicotine: nicotineResourceSchema,
	particleDescription: particleDescriptionResourceSchema,
	particleDescriptionCollection: particleDescriptionCollectionResourceSchema,
	playerCarColours: playerCarColoursResourceSchema,
	registry: registryResourceSchema,
	polygonSoupList: polygonSoupListResourceSchema,
	propGraphicsList: propGraphicsListResourceSchema,
	propInstanceData: propInstanceDataResourceSchema,
	propPhysics: propPhysicsResourceSchema,
	renderable: renderableResourceSchema,
	snapshotData: snapshotDataResourceSchema,
	splicer: splicerResourceSchema,
	staticSoundMap: staticSoundMapResourceSchema,
	streetData: streetDataResourceSchema,
	texture: textureResourceSchema,
	textureNameMap: textureNameMapResourceSchema,
	trafficData: trafficDataResourceSchema,
	triggerData: triggerDataResourceSchema,
	vehicleList: vehicleListResourceSchema,
	vfxMeshCollection: vfxMeshCollectionResourceSchema,
	vfxPropCollection: vfxPropCollectionResourceSchema,
	wheelList: wheelListResourceSchema,
	worldPainter2D: worldPainter2DResourceSchema,
	zoneList: zoneListResourceSchema,
};

export function getSchemaByKey(key: string): ResourceSchema | undefined {
	return RESOURCE_SCHEMAS[key];
}
