// Lookup table from handler key → ResourceSchema. Generated by hand;
// every key here points at the schema that drives the schema-editor
// hierarchy / inspector for that resource type. Keys not listed here have
// no schema yet (renderable's tree comes from RenderablePage's synthetic
// root, polygonSoupList from PolygonSoupListPage's bundled picker, etc.).
//
// Used by the WorkspaceEditor to look up a resource's schema when the
// user selects it in the tree, so the right-hand inspector can render the
// generic schema form for any resource type.

import type { ResourceSchema } from '../types';
import { aiSectionsResourceSchema } from './aiSections';
import { challengeListResourceSchema } from './challengeList';
import { iceTakeDictionaryResourceSchema } from './iceTakeDictionary';
import { instanceListResourceSchema } from './instanceList';
import { languageResourceSchema } from './language';
import { playerCarColoursResourceSchema } from './playerCarColours';
import { polygonSoupListResourceSchema } from './polygonSoupList';
import { propGraphicsListResourceSchema } from './propGraphicsList';
import { propInstanceDataResourceSchema } from './propInstanceData';
import { propPhysicsResourceSchema } from './propPhysics';
import { renderableResourceSchema } from './renderable';
import { staticSoundMapResourceSchema } from './staticSoundMap';
import { streetDataResourceSchema } from './streetData';
import { textureResourceSchema } from './texture';
import { trafficDataResourceSchema } from './trafficData';
import { triggerDataResourceSchema } from './triggerData';
import { vehicleListResourceSchema } from './vehicleList';
import { zoneListResourceSchema } from './zoneList';

const RESOURCE_SCHEMAS: Record<string, ResourceSchema> = {
	aiSections: aiSectionsResourceSchema,
	challengeList: challengeListResourceSchema,
	iceTakeDictionary: iceTakeDictionaryResourceSchema,
	instanceList: instanceListResourceSchema,
	language: languageResourceSchema,
	playerCarColours: playerCarColoursResourceSchema,
	polygonSoupList: polygonSoupListResourceSchema,
	propGraphicsList: propGraphicsListResourceSchema,
	propInstanceData: propInstanceDataResourceSchema,
	propPhysics: propPhysicsResourceSchema,
	renderable: renderableResourceSchema,
	staticSoundMap: staticSoundMapResourceSchema,
	streetData: streetDataResourceSchema,
	texture: textureResourceSchema,
	trafficData: trafficDataResourceSchema,
	triggerData: triggerDataResourceSchema,
	vehicleList: vehicleListResourceSchema,
	zoneList: zoneListResourceSchema,
};

export function getSchemaByKey(key: string): ResourceSchema | undefined {
	return RESOURCE_SCHEMAS[key];
}
